[package]
name = "a01_juniper_hello"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.5.1"
actix-web-lab = "0.20.2"
env_logger = "0.11.3"
juniper = "0.16.1"
log = "0.4.21"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros"] }
